remote_theme: nrandecker/particle

# Site settings
description: A weeklong conference in Philly featuring pumpcon on Saturday
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:3000" # the base hostname & protocol for your site

# User settings
username: NousCon
user_description: A weeklong conference in Philly featuring pumpcon on Saturday
user_title: 2019
email: spam@nouscon.org
twitter_username: nouscon
github_username:  nouscon
